name: hello-world
on: push

env:
  SPECTRAL_DSN: https://spu-e547a47732c946f7b8a1c951e459b845@get.spectralops.io

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and run Spectral CI
        uses: spectralops/spectral-github-action@v3
        with:
          spectral-dsn: https://spu-e547a47732c946f7b8a1c951e459b845@get.spectralops.io
          spectral-args: scan --include-tags base,audit
