name: hello-world
on: push

env:
  SPECTRAL_DSN: https://spu-611d48d6aea54688810e914873eeeaf1@get.spectralops.io

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:    
      security-events: write      
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - run: git diff --name-only ${{ github.event.before }} ${{ github.sha }}
      - name: Install and run Spectral CI
        uses: spectralops/spectral-github-action@v3
        with:
          spectral-dsn: https://spu-611d48d6aea54688810e914873eeeaf1@get.spectralops.io
          spectral-args: scan --include-tags base,audit --json-v2 results.json --ok     
